# Generated by Django 3.0.3 on 2020-08-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='内容')),
                ('state', models.IntegerField(choices=[(1, '未実行'), (2, '実行中'), (3, '終了')], verbose_name='状態')),
            ],
        ),
    ]
